### ISSUE TITLE
Structs should use pointers for fields

### ISSUE THREAD

**Issue by martinsefcik** [xanzy/go-gitlab#29] opened 2015-12-19 14:31 UTC
I think we should change fields in structs to use pointers and so distinguish between nil and empty values.

The same approach is used in go-github repository.
Here you can find detailed blog why it is good to use pointers:
https://willnorris.com/2014/05/go-rest-apis-and-pointers

It's also problem in go-gitlab.
For example you cannot edit existing project's description and change it to empty string, because empty description value will never be sent to server (will be omitted).

What do you think ?

**Comment by svanharmelen** [comment] 2015-12-28 11:29
I think I agree, but want to think about it for another couple of days before we start changing stuff.

And when we do start changing this, I prefer to change it with one PR for the whole package. This way everything stays consistent and we don't have two different patterns at the same time.

So I'll come back on this one, but like I said I think I agree :grinning:

**Comment by svanharmelen** [comment] 2016-01-21 08:10
@martinsefcik after thinking about this for a little while I agree that we would need to change this. The problem is of course that a change like this would be a breaking change, but I think there is no way to get around that...

So let's go ahead and (when time permits) start the work on this one :grinning:

Since it's a breaking change I do prefer one big PR for the whole change and some minimal helper functions that can be used by users of this package to similar to what AWS has done https://github.com/aws/aws-sdk-go/blob/master/aws/convert_types.go

With that's in place I think the burden of updating code does not outweigh the benefits from having a better API on which we can continue to build for the future.

**Comment by martinsefcik** [comment] 2016-01-24 16:18
If I will have some free time I can start working on it.

**Comment by svanharmelen** [comment] 2016-07-26 16:44
Fixed by PR #66

**Closed by svanharmelen** 2016-07-26 16:44 UTC

**Comment by martinsefcik** [comment] 2016-07-26 18:29
👍

**Comment by mvdan** [comment] 2016-07-27 08:56
This is a rather surprising change, mostly because the API now seems very verbose and repetitive for no reason. Then again, I can't think of a better solution and it seems like `go-github` does the same.

**Comment by svanharmelen** [comment] 2016-07-27 09:02
@mvdan I understand your point and I partly agree... Yet I don't agree it is "for no reason" as certain use cases do not work without this change...

And yes, I too cannot think of a better/other way so following the `go-github` approach feels like the best way forward.

**Comment by mvdan** [comment] 2016-07-27 09:04
> Yet I don't agree it is "for no reason" as certain use cases do not work without this change...

I meant to say "at first glance" :) It seems like a non-idiomatic way to do things, but as said it seems like the only way.

**Comment by svanharmelen** [comment] 2016-07-27 09:09
Agree... Not the most idiomatic, yet there are quite a couple of packages using such an approach (mostly API client packages of course). See for example this blog from 2 years ago already: https://willnorris.com/2014/05/go-rest-apis-and-pointers
