### ISSUE TITLE
I don't think we should use omitempty

### ISSUE THREAD

**Issue by henjue** [xanzy/go-gitlab#30] opened 2016-01-02 10:44 UTC
If I need to set up a project for the private, because used omitempty VisibilityLevel EditProjectOptions tag, so ignore 0. So can not set the project for the private

Ps:EditProjectOptions in the Public is the time is false

**Comment by svanharmelen** [comment] 2016-01-03 10:35
I guess this is a good example of why we should implement the change (using pointers in structs) suggested/discussed in issue #29. So please follow that issue as it will fix your problem as well.

I'll close this one as a duplicate of #29 as they both address the same problem.

**Closed by svanharmelen** 2016-01-03 10:35 UTC
