### ISSUE TITLE
PUT redirects to https not followed

### ISSUE THREAD

**Issue by alinadonisa** [xanzy/go-gitlab#523] opened 2018-11-29 15:22 UTC
I have a GitLab instance that is behind an nginx that redirects all HTTP requests to HTTPS.

GET requests seem to work on HTTP, but PUT requests never reach the server.

When I try to edit the access level using the code bellow and HTTP  the method returns no error, and the member field is populated with the existing access level. No update is executed but the requests returns 200
```
        options := gitlab.EditProjectMemberOptions{
		AccessLevel: &accessLevel,
	}
	member, rsp, err := gitClient.ProjectMembers.EditProjectMember(project.ID, member.ID, &options)
	if err != nil {
		return nil, err
	}
```

**Comment by svanharmelen** [comment] 2018-11-29 19:16
Hi @alinadonisa! Did you try to exec these API calls with cURL to see if it then works as expected?

These are some basic examples here that should give enough info on how to make the calls you want to test: https://docs.gitlab.com/ce/api/#basic-usage

**Comment by adrianharabula** [comment] 2018-11-29 20:49
Hello @svanharmelen . curl calls with -L parameter to follow https redirect works with no problem.

**Comment by svanharmelen** [comment] 2018-11-30 08:44
Ok... Another question, how are you creating the Gitlab client?

**Comment by adrianharabula** [comment] 2018-12-01 12:32
Here is an example to replicate the problem:
```go
package main

import (
  "log"

  "github.com/xanzy/go-gitlab"
)

func main() {
  // gitlab client
  // works with https, but not with http link
  // http link does not follow redirect to https
  git := gitlab.NewClient(nil, "token")
  git.SetBaseURL("http://gitlab.url/api/v4")

  // here we try to set member project permissions to Reporter
  accessLevel := gitlab.ReporterPermissions
    options := gitlab.EditProjectMemberOptions{
    AccessLevel: &accessLevel,
  }

  // program finishes successfully with no errors, but permissions unchanged
  _, _, err := git.ProjectMembers.EditProjectMember(project.ID, member.ID, &options)
  if err != nil {
    log.Fatal(err)
  }
}
```
The above example works if changing gitlab url to https. If using http, program seems to execute fine but permission remains unchanged. On gitlab side no request hits the server (API request not in logs)

**Comment by svanharmelen** [comment] 2018-12-27 11:41
@alinadonisa and @adrianharabula I think I found the root cause this problem.

I finally had some time to test with this and when I did, I noticed that Gitlab uses a 307 status code to indicate a redirect. I looked up the support for that in the Go source code which lead me to this file: https://golang.org/src/net/http/client.go.

If you look at lines 435 to 460 you can see that a 307 or 308 redirect requires re-sending the body. The `http.Request` type got a new field called `GetBody` that needs to be set in order to enable re-sending the body, but that new field was not set by the `go-gitlab` package.

I just added this and assume it will fix this issue. Please let me know if it's indeed fixed now or that I need to take another look. Thanks!

**Closed** 2018-12-27 11:41 UTC
