### ISSUE TITLE
Panic in Terraform Provider v3.5.0 when reading protected branches

### ISSUE THREAD

**Issue by hobti01** [xanzy/go-gitlab#1118] opened 2021-03-31 10:16 UTC
Since a few days we've been receiving the panic below in the terraform provider.  I'm not sure if they should have more protection around the returned struct or the issue should be resolved in `go-gitlab`.

Downstream offending line is here: https://github.com/gitlabhq/terraform-provider-gitlab/blob/v3.5.0/gitlab/resource_gitlab_branch_protection.go#L120

Please let me know if this issue should be relocated to the provider:

```
panic: runtime error: index out of range [0] with length 0
2021-03-31T09:55:54.545Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 
2021-03-31T09:55:54.545Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: goroutine 3002 [running]:
2021-03-31T09:55:54.545Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: github.com/gitlabhq/terraform-provider-gitlab/gitlab.resourceGitlabBranchProtectionRead(0xc00013d180, 0x109b1c0, 0xc00009c380, 0xc00013d180, 0x0)
2021-03-31T09:55:54.545Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	github.com/gitlabhq/terraform-provider-gitlab/gitlab/resource_gitlab_branch_protection.go:120 +0x73c
2021-03-31T09:55:54.545Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000118a20, 0xc0002eeb90, 0x109b1c0, 0xc00009c380, 0xc0004fe488, 0x0, 0x0)
2021-03-31T09:55:54.545Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:460 +0x129
2021-03-31T09:55:54.545Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000128148, 0x12e31a0, 0xc00014a9c0, 0xc0007bfb00, 0xc000128148, 0xc00014a9c0, 0xc00065cb78)
2021-03-31T09:55:54.545Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:525 +0x3dd
2021-03-31T09:55:54.545Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1103140, 0xc000128148, 0x12e31a0, 0xc00014a9c0, 0xc0007bfaa0, 0x0, 0x12e31a0, 0xc00014a9c0, 0xc000638210, 0xad)
2021-03-31T09:55:54.545Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
2021-03-31T09:55:54.545Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000103b00, 0x12ec720, 0xc0007aa300, 0xc000600400, 0xc000117ec0, 0x18c88d0, 0x0, 0x0, 0x0)
2021-03-31T09:55:54.545Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
2021-03-31T09:55:54.546Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: google.golang.org/grpc.(*Server).handleStream(0xc000103b00, 0x12ec720, 0xc0007aa300, 0xc000600400, 0x0)
2021-03-31T09:55:54.546Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd34
2021-03-31T09:55:54.546Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002da010, 0xc000103b00, 0x12ec720, 0xc0007aa300, 0xc000600400)
2021-03-31T09:55:54.546Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa5
2021-03-31T09:55:54.546Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-03-31T09:55:54.546Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa5
2021-03-31T09:55:54.547Z [DEBUG] plugin: plugin process exited: path=/var/run/terraform/.terraform/plugins/linux_amd64/terraform-provider-gitlab_v3.5.0 pid=5646 error="exit status 2"
2021/03/31 09:55:54 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
```

edit: Already reported downstream  https://github.com/gitlabhq/terraform-provider-gitlab/issues/415

**Comment by svanharmelen** [comment] 2021-03-31 11:02
This panic is not caused by this package, so good that you opened an issue with the provider as well.

In the provider they make an assumption that `PushAccessLevels` will always contains a value so they try to index the slice while the slice is `nil`. So they first need to test if the value is not `nil` (`pb.PushAccessLevels != nil` or probably even better in this case `len(pb.PushAccessLevels) > 0`) and only then try to index it...

I'll close this issue for now, if needed feel free to reopen it.

**Closed by svanharmelen** 2021-03-31 11:02 UTC
