### ISSUE TITLE
Most gitlab APIs support urlencoded strings and this is broken when used in go-gitlab

### ISSUE THREAD

**Issue by pschwartz** [xanzy/go-gitlab#632] opened 2019-05-31 16:06 UTC
The liberal use of the `pathEscape` function leads to issues when using the gitlab api to query things that are path based.

`group/subgroup/project` is valid

`curl --header "PRIVATE-TOKEN: ${token}" https://gitlab.com/api/v4/projects/group%2Fsubgroup%2Fproject` can be used to query it.

But using `gitlab.Client.Projects.GetProjects("group/subgroup/project")` or  `gitlab.Client.Projects.GetProjects("group%2Fsubgroup%2Fproject")` fails to find the searched for group.

These should work in many APIs, a few examples are groups, projects, repository_files

**Comment by pschwartz** [comment] 2019-05-31 16:08
Here is an example right from the gitlab api docs.

https://docs.gitlab.com/ee/api/repository_files.html#get-file-from-repository

`file_path (required) - Url encoded full path to new file. Ex. lib%2Fclass%2Erb`

**Comment by pschwartz** [comment] 2019-05-31 16:15
A hack around the issue is to enforce encoding prior to calling the go-gitlab functions. Has anyone else seen this behavior?

**Comment by svanharmelen** [comment] 2019-05-31 16:56
@pschwartz if I look at the [repository_files](https://github.com/xanzy/go-gitlab/blob/master/repository_files.go) methods, I see that `pathEscape` (like in all other methods) is only used to escape the `project` or `group`. The given `fileName` is escaped using `url.PathEscape` which should properly escape the path following the requirements of the Gitlab API.

> curl --header "PRIVATE-TOKEN: ${token}" https://gitlab.com/api/v4/projects/group%2Fsubgroup%2Fproject can be used to query it.

The fact that this works, means (at least to me) that escaping is not the issue. Can you share any addition info? Maybe a minimal example and the exact error message?

**Comment by svanharmelen** [comment] 2019-06-16 15:03
@pschwartz do you have any updates or additional details for this one?

**Comment by svanharmelen** [comment] 2019-08-15 08:17
@pschwartz  any update on this?

**Comment by ahuret** [comment] 2019-10-14 13:32
Hi @svanharmelen !  I got a case where url encoding seems to break gitlab api.

Here I want to list issues with a label filter:

```
gitlab.Issues.ListProjectIssues(projectID, &gitlab.ListProjectIssuesOptions{Labels: &gitlab.Labels{"my label"}})
```
result to => 
```
curl -H "Private-Token: XXXXXXXXXX" http://gitlab:8081/api/v4/projects/1/issues?labels=%5Bmy+label%5D
```
where
`%5Bmy+label%5D` decoded is `[my+label]` but gitlab docs says labels slice should be separated by commas (https://docs.gitlab.com/ce/api/issues.html#list-issues).
I can see go-gitlab `type Labels struct` implements Marshaller
```
func (l *Labels) MarshalJSON() ([]byte, error) {
	return json.Marshal(strings.Join(*l, ","))
}
```

but it's not use cause `GET`s requests use
```
if opt != nil {
	q, err := query.Values(opt)
	if err != nil {
		return nil, err
	}
	u.RawQuery = q.Encode()
}
```

don't know how to solve this, have you got an idea ? thanks :)

**Comment by ahuret** [comment] 2019-10-14 13:51
seems it's proken by 446d35380041b926c2a08757cace1a1e291ff042

**Comment by svanharmelen** [comment] 2019-10-14 14:01
Should be fixed by 0784142ea5790a0ebc89fde2c632e280690ae4b2 Sorry for the inconvenience!

**Comment by ahuret** [comment] 2019-10-14 14:03
I don't think it will fix issue, problem here is about pointer. If I replace `*Labels` by `Labels` it works

**Comment by svanharmelen** [comment] 2019-10-14 14:09
Did you try it?

**Comment by ahuret** [comment] 2019-10-14 14:09
Yep, with and withou `comma` and it works when `Labels`  is not a pointer

**Comment by ahuret** [comment] 2019-10-14 14:13
better to use comma, it's more gitlab way. `labels=a,b,c` vs `labels=a&labels=b`

**Comment by svanharmelen** [comment] 2019-10-14 14:17
Hmm... I don't follow what you are saying.

```
gitlab.Issues.ListProjectIssues(projectID, &gitlab.ListProjectIssuesOptions{Labels: &gitlab.Labels{"a", "b", "c"}})
```

This should work and give you `a,b,c` right? In your example you used:

```
gitlab.Issues.ListProjectIssues(projectID, &gitlab.ListProjectIssuesOptions{Labels: &gitlab.Labels{"my label"}})
```

Which is 1 label right?

**Comment by ahuret** [comment] 2019-10-14 14:29
check https://play.golang.org/p/l6tCHGMtBtZ

and btw: https://github.com/google/go-querystring/issues/26 says non-nil pointer to slice are not handle properly by the go-querystring library, not exactly in our case but seems there are unexpected behaviors.

**Comment by ahuret** [comment] 2019-10-14 14:45
we should go back to `Labels Labels `url:"labels,comma,omitempty" json:"labels,omitempty"`` for at least `GET`  funcs:

`ListIssuesOptions`
`ListGroupIssuesOptions`
`ListProjectIssuesOptions`

`PUT` and `POST` are ok

**Comment by svanharmelen** [comment] 2019-10-14 19:48
All these ^^ comments are deleted here as it turned out that they had nothing to do with this issue. It was in fact related to PR #713 and is not partially rolled back in #715

**Comment by svanharmelen** [comment] 2020-02-05 12:10
I'm going to close this one because of the leak of response. Feel free to reopen it when you want to follow up on the issue.

**Closed by svanharmelen** 2020-02-05 12:10 UTC
Labels: waiting

**Comment by fi0rini** [comment] 2022-08-11 02:31
if anyone else lands here it still doesn't work 2 years later and i might be able to make a PR to the request client at some point but I'm too busy now. I used this work around (it's not necessarily pretty)
```go
groupName := "group/subgroup/subsubgroup"
groups, _, err := gitClient.Groups.SearchGroup(groupName)
checkError(err)
var group *gitlab.Group
for _, g := range groups {
	if g.FullPath == groupName {
		group, _, err = gitClient.Groups.GetGroup(g.ID, &gitlab.GetGroupOptions{})
		checkError(err)
		break
	}
}
if group == nil {
    // you can fail or do whatever because the group doesn't exist
}
```
