### ISSUE TITLE
Creating/Updating an Issue with a Label does not apply the label

### ISSUE THREAD

**Issue by bertoldia** [xanzy/go-gitlab#1742] opened 2023-06-21 22:30 UTC
Creating an issue with the following sample code: 
```go

const (
    ProjectID = "some-project-id"
    Label = "some-label"
)
...
issue, _, err := gitlab.Client.Issues.CreateIssue(ProjectID, &gitlab.CreateIssueOptions{
		Title:       gitlab.String("a title"),
		Description: gitlab.String("a description"),
		Labels:      &gitlab.Labels{Label},
})
```
successfully creates an issue with the specified title and description, but does not apply the label (which definitely already exists) to the new issue.

Similarly, this
```go
_, _, err := a.api.Issues.UpdateIssue(a.ProjectID, issue.IID, &gitlab.UpdateIssueOptions{
	Labels: &gitlab.Labels{Label},
})
```
Does not apply the label to the issue.

In contrast, for example, these work:
```sh
> glab issue create -t "sdfjghsldkfhgslkjdgfh" -l some-unique-label
>  glab issue update 17 -l some-unique-label
```
Using `v1.4.3`

Hopefully this is user error, but it doesn't look like it.

**Comment by vntw** [comment] 2023-06-26 10:26
Works for me, I've been using labels when creating issue for some time without issues in v0.81 and now v0.86. Tested the basic gist of your code and worked:

```go
package main

import (
	"fmt"
	"log"

	"github.com/xanzy/go-gitlab"
)

const (
	ProjectID = "…"
	Label     = "L1"
)

func main() {
	git, err := gitlab.NewClient("…")
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}

	issue, _, err := git.Issues.CreateIssue(ProjectID, &gitlab.CreateIssueOptions{
		Title:       gitlab.String("a title"),
		Description: gitlab.String("a description"),
		Labels:      &gitlab.Labels{Label},
	})
	if err != nil {
		log.Fatalf("Failed to create issue: %v", err)
	}
	fmt.Println(issue.WebURL)
}
```

<img width="315" alt="image" src="https://github.com/xanzy/go-gitlab/assets/502368/0bc76e5a-39f0-4b12-a661-aac05b9eb556">

---

Maybe there's a typo in your label name?

**Comment by svanharmelen** [comment] 2023-07-16 07:31
Since we didn't receive feedback and cannot reproduce the problem, I'm going to close this issue.

**Closed by svanharmelen** 2023-07-16 07:31 UTC

**Comment by bertoldia** [comment] 2023-07-16 17:02
Sorry, I haven't had a chance to test this again. If I still encounter it I reopen the issue with more information.
