### ISSUE TITLE
ListPersonalAccessTokens API  , return Token filed is always empty

### ISSUE THREAD

**Issue by sunyaf** [xanzy/go-gitlab#1658] opened 2023-02-23 02:01 UTC
ListPersonalAccessTokens API  , return Token filed is always empty

**Comment by sunyaf** [comment] 2023-02-23 02:19
tokens, response, err := git.PersonalAccessTokens.ListPersonalAccessTokens(&gitlab.ListPersonalAccessTokensOptions{UserID: &uid})

gitlab.PersonalAccessToken{ID:3, Name:"test", Revoked:false, CreatedAt:time.Time{wall:, ext:}, Scopes:["api" "read_api" "read_user" "read_repository" "write_repository"], UserID:2, Active:true, ExpiresAt:gitlab.ISOTime{wall:, ext:}, Token:""}

Token is empty

**Comment by svanharmelen** [comment] 2023-02-23 09:00
Can you make the same call successfully using cURL?

**Comment by sunyaf** [comment] 2023-02-23 11:16
> 
It can succeed, but the result  returned  Token  is again empty.

**Comment by svanharmelen** [comment] 2023-02-23 11:36
If the result (tokens) are also empty when making the call using cURL, the problem is nog related to the package but instead to the GitLab API...

**Comment by svanharmelen** [comment] 2023-07-16 07:36
Closing this one as it's not related to this package, but the GitLab API

**Closed by svanharmelen** 2023-07-16 07:36 UTC
